### ISSUE TITLE
please re-instate copyright headers

### ISSUE THREAD

**Issue by bradrydzewski** [banzaicloud/cicd-go#1]
👋 hey there, it appears the copyright headers were removed from the source code [1] in many of these files. I would kindly ask that you retain the origin copyright headers, in compliance with section 4.c of the Apache License. Thanks!

[1] https://github.com/drone/drone-go/commit/f543e903b5258a10a8366be9b54eff9cbbe27f61#diff-97dc6e5c80e7b897be6a7200517c396c

**Comment by bonifaido** [comment]
Hi @bradrydzewski, thanks for checking this, sorry somehow this has been wiped out, I have added them back! Thanks again.
